# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-02 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('token', models.CharField(max_length=50)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
    ]
